---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-symphonyapp
  namespace: sicreji

spec:
  replicas: 1
  selector:
    matchLabels:
      app: symp
  # pod template
  template:
    metadata:
      labels:
        app: symp
    spec:
      containers:
        - name: webapp
          image: opusidea/luminess-projet3:0.2
          env:
          - name: DATABASE_URL
            value: "mysql://root:supersecure@mariadb-svc:3306/formation?serverVersion=mariadb-10.3.36"
---
kind: Service
apiVersion: v1
metadata:
  name: symphonyapp-svc
  namespace: sicreji

spec:
  type: LoadBalancer # connectivité externe sur AWS ?
  selector:
    app: symph
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80